version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "daiara"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-d3rwkgc91gu1"
s3_prefix = "daiara"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
